apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: justatest-hpa
  labels:
    app: justatest
    version: 0.0.1
    backstage.io/kubernetes-id: justatest
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: justatest
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75